#!/usr/bin/env python3
"""Compile a self-contained Gemini Kendo SRT Translator agent package.

This script uses the agent compiler to create a distributable package
for the kendo SRT translation task. The resulting package includes:

- agent.py: Executable translation script
- config.json: Modifiable configuration
- storage/: Auth state (gemini_storage_state.json)
- kendo_dict.md: Kendo dictionary
- requirements.txt: Python dependencies
- source_spec.json: Recompilation spec
- README.md: Usage instructions

Usage:
    python scripts/compile_kendo_translator.py [--output-dir DIR]
"""

import argparse
import json
import shutil
import sys
import textwrap
from pathlib import Path

# Add project root for imports
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from universal_agents.compiler import (
    AgentCompiler,
    AgentPackager,
    CapabilityResolver,
    CompiledAgent,
    ConfigBuilder,
    AgentAssembler,
    ResolvedComponents,
    UserRequirements,
)


def compile_kendo_translator(output_dir: Path) -> Path:
    """Compile and package the Gemini kendo SRT translator agent."""

    # 1. Define requirements
    req = UserRequirements(
        use_case="translation",
        needs_file_upload=False,
        needs_thinking=False,
        needs_json_output=False,
        cost_sensitivity="free",
        provider_preference="gemini",
        output_format="package",
        package_dir=str(output_dir),
        package_name="gemini_kendo_srt_translator",
        auth_available={"gemini_storage": True},
    )
    req.apply_use_case_defaults()

    # 2. Resolve components
    resolver = CapabilityResolver()
    components = resolver.resolve(req)

    # 3. Override config for kendo SRT task
    config_kwargs = {
        "headless": True,
        "timeout": 600,
        "max_turns_per_conversation": 20,
        "source_language": "ja",
        "target_language": "en",
        "translation_mode": "transcript",
        "chunk_size": 2000,
        "overlap_chars": 100,
        "required_model": "pro",
        "storage_state": str(PROJECT_ROOT / "storage" / "gemini_storage_state.json"),
    }

    # 4. Create compiled agent
    compiled = CompiledAgent(
        provider="gemini",
        agent_class_name=components.agent_class_name,
        config_class_name=components.config_class_name,
        config_kwargs=config_kwargs,
        capabilities=["translation", "file_upload", "model_selection", "rate_limit_detection"],
        script="# Replaced by custom script below",
    )

    # 5. Package it
    packager = AgentPackager(project_root=PROJECT_ROOT)
    pkg_dir = packager.package(compiled, components, req, output_dir, "gemini_kendo_srt_translator")

    # 6. Copy the kendo dictionary into the package
    dict_src = PROJECT_ROOT / "storage" / "test_srt_files" / "Trilingual Kendo Dictionary.md"
    if dict_src.exists():
        shutil.copy2(dict_src, pkg_dir / "kendo_dict.md")

    # 7. Write the custom production run script (replaces generic agent.py)
    _write_run_script(pkg_dir)

    # 8. Update config.json with kendo-specific fields
    config_path = pkg_dir / "config.json"
    config = json.loads(config_path.read_text())
    config["kendo"] = {
        "dictionary_file": "kendo_dict.md",
        "lines_per_conversation": 400,
        "lines_per_turn": 50,
        "srt_input_dir": "srt_files/",
        "srt_output_dir": "translated/",
    }
    config_path.write_text(json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8")

    # 9. Create input/output directories
    (pkg_dir / "srt_files").mkdir(exist_ok=True)
    (pkg_dir / "translated").mkdir(exist_ok=True)
    (pkg_dir / "progress").mkdir(exist_ok=True)

    print(f"\n✅ Package created at: {pkg_dir}")
    print(f"   Files: {list(p.name for p in sorted(pkg_dir.iterdir()))}")
    print(f"\n   To use:")
    print(f"   1. Copy SRT files into: {pkg_dir / 'srt_files/'}")
    print(f"   2. Run: cd {pkg_dir} && python agent.py srt_files/YOUR_FILE.srt")
    print(f"   3. Or batch: cd {pkg_dir} && python agent.py --all")
    return pkg_dir


def _write_run_script(pkg_dir: Path) -> None:
    """Write the production agent.py for kendo SRT translation."""
    script = textwrap.dedent('''\
        #!/usr/bin/env python3
        """Kendo SRT Translator — Self-contained Gemini translation agent.

        Translates Japanese SRT subtitle files to English using Gemini Pro
        with kendo terminology dictionary context.

        Generated by universal-agents compiler.
        Edit config.json to change behavior.

        Usage:
            python agent.py FILE.srt              # Translate one file
            python agent.py --all                  # Translate all *.ja.srt in srt_files/
            python agent.py --resume               # Resume after rate limit
            python agent.py --visible FILE.srt     # Show browser
            python agent.py --login                # Capture fresh login session
        """

        import argparse
        import asyncio
        import json
        import logging
        import re
        import sys
        import time
        from datetime import datetime
        from pathlib import Path

        SCRIPT_DIR = Path(__file__).resolve().parent

        # ---------------------------------------------------------------------------
        # Load config
        # ---------------------------------------------------------------------------
        with open(SCRIPT_DIR / "config.json", encoding="utf-8") as f:
            CONFIG = json.load(f)

        _kwargs = dict(CONFIG["config_kwargs"])

        # Resolve storage state relative to package
        _state_name = Path(_kwargs.get("storage_state", "")).name if _kwargs.get("storage_state") else ""
        _state = SCRIPT_DIR / "storage" / "gemini_storage_state.json"
        if _state.exists():
            _kwargs["storage_state"] = str(_state)
        elif _state_name:
            _s = SCRIPT_DIR / "storage" / _state_name
            if _s.exists():
                _kwargs["storage_state"] = str(_s)

        _kendo = CONFIG.get("kendo", {})
        DICT_FILE = SCRIPT_DIR / _kendo.get("dictionary_file", "kendo_dict.md")
        LINES_PER_CONVO = _kendo.get("lines_per_conversation", 400)
        LINES_PER_TURN = _kendo.get("lines_per_turn", 50)
        SRT_INPUT_DIR = SCRIPT_DIR / _kendo.get("srt_input_dir", "srt_files/")
        SRT_OUTPUT_DIR = SCRIPT_DIR / _kendo.get("srt_output_dir", "translated/")
        PROGRESS_DIR = SCRIPT_DIR / "progress"

        logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
        logger = logging.getLogger(__name__)

        # ---------------------------------------------------------------------------
        # Imports (universal_agents must be on sys.path or installed)
        # ---------------------------------------------------------------------------
        from universal_agents.providers.gemini.config import GeminiTranslatorConfig
        from universal_agents.providers.gemini.translator import (
            GeminiTranslatorAgent,
            ProgressState,
            RateLimitError,
            TranslationChunk,
        )
        from universal_agents.core.srt_utils import parse_srt_blocks, chunk_srt_text
        from universal_agents.core.kendo_context import (
            build_kendo_srt_system_prompt,
            build_kendo_continue_prompt,
            build_kendo_new_conversation_prompt,
        )


        def count_srt_blocks(text: str) -> int:
            return len(re.findall(r"^\\d+$", text, re.MULTILINE))


        # ---------------------------------------------------------------------------
        # Login helpers
        # ---------------------------------------------------------------------------

        async def _save_cookies(page) -> None:
            """Save browser cookies to storage/gemini_storage_state.json."""
            storage_dir = SCRIPT_DIR / "storage"
            storage_dir.mkdir(parents=True, exist_ok=True)
            state_file = storage_dir / "gemini_storage_state.json"

            ctx = page.context
            state = await ctx.storage_state()
            state_file.write_text(
                json.dumps(state, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
            logger.info("Storage state saved: %s", state_file)

            # Update config to point to new storage state
            _kwargs["storage_state"] = str(state_file)


        async def capture_login() -> bool:
            """Open a visible browser, navigate to Google login, then verify on Gemini."""
            logger.info("Opening browser for Google login...")
            config = GeminiTranslatorConfig(**{**_kwargs, "headless": False})
            agent = GeminiTranslatorAgent(config)

            try:
                async with agent:
                    page = await agent._agent.browser_mgr.ensure_page()

                    # Check if already logged in to Gemini
                    if await agent.check_logged_in():
                        logger.info("Already logged in!")
                        await _save_cookies(page)
                        return True

                    # Navigate to Google login page
                    await page.goto("https://accounts.google.com/signin")
                    await page.wait_for_timeout(2000)

                    print("\\n" + "=" * 60)
                    print("  GOOGLE LOGIN")
                    print("=" * 60)
                    print("  Please log in to your Google account in the browser window.")
                    print("  After login, the agent will navigate to Gemini automatically.")
                    print("  Waiting for login (checking every 5s)...")
                    print("=" * 60 + "\\n")

                    # Wait for Google login to complete by checking URL changes
                    for attempt in range(120):  # 10 minutes
                        await asyncio.sleep(5)
                        url = page.url
                        if "accounts.google.com/signin" not in url and "accounts.google.com/v3/signin" not in url:
                            logger.info("Google login appears complete (URL: %s)", url[:80])
                            break
                        if attempt % 12 == 11:
                            print(f"  Still waiting for Google login... ({(attempt + 1) * 5}s)")
                    else:
                        logger.error("Google login timeout after 10 minutes")
                        return False

                    # Now navigate to Gemini to verify and capture cookies
                    logger.info("Navigating to Gemini...")
                    await page.goto("https://gemini.google.com")
                    try:
                        await page.wait_for_selector(
                            "div[contenteditable='true']", state="visible", timeout=30_000,
                        )
                    except Exception:
                        await page.wait_for_timeout(5000)

                    if await agent.check_logged_in():
                        logger.info("Gemini login verified!")
                        await _save_cookies(page)
                        print("\\n  Login successful! Cookies saved.\\n")
                        return True

                    # Give extra time if Gemini still shows sign-in
                    logger.warning("Gemini not yet authenticated, waiting...")
                    for retry in range(12):
                        await asyncio.sleep(5)
                        if await agent.check_logged_in():
                            await _save_cookies(page)
                            print("\\n  Login successful! Cookies saved.\\n")
                            return True

                    logger.error("Logged into Google but Gemini auth failed")
                    return False
            except Exception as e:
                logger.error("Login capture failed: %s", e)
                return False


        async def verify_login(agent: GeminiTranslatorAgent, visible: bool) -> bool:
            """Verify login, optionally redirecting to Google login in visible mode."""
            logged_in = await agent.check_logged_in()
            if logged_in:
                return True

            if not visible:
                logger.error(
                    "Not logged in to Gemini. Run with --login first, "
                    "or use --visible to log in manually."
                )
                return False

            page = await agent._agent.browser_mgr.ensure_page()
            logger.info("Not logged in — redirecting to Google login...")
            await page.goto("https://accounts.google.com/signin")
            await page.wait_for_timeout(2000)

            print("\\n  Not logged in. Please log in to Google in the browser window.")
            print("  After login, the agent will navigate back to Gemini.")
            print("  Waiting for login (checking every 5s)...\\n")

            for attempt in range(60):
                await asyncio.sleep(5)
                url = page.url
                if "accounts.google.com/signin" not in url and "accounts.google.com/v3/signin" not in url:
                    logger.info("Google login complete (URL: %s)", url[:80])
                    await page.goto("https://gemini.google.com")
                    try:
                        await page.wait_for_selector(
                            "div[contenteditable='true']", state="visible", timeout=30_000,
                        )
                    except Exception:
                        await page.wait_for_timeout(5000)
                    if await agent.check_logged_in():
                        await _save_cookies(page)
                        return True
                    for retry in range(6):
                        await asyncio.sleep(5)
                        if await agent.check_logged_in():
                            await _save_cookies(page)
                            return True
                    logger.error("Google login succeeded but Gemini auth failed")
                    return False
                if attempt % 6 == 5:
                    print(f"  Still waiting... ({(attempt + 1) * 5}s)")

            logger.error("Login timeout after 5 minutes")
            return False


        async def verify_model(agent: GeminiTranslatorAgent, visible: bool) -> bool:
            """Verify the correct model is selected, retry if needed."""
            required = (agent.config.required_model or "").lower()
            if not required:
                return True

            current = await agent.detect_current_model()
            if current and required in current:
                logger.info("Model verified: %s", current)
                return True

            logger.warning("Expected '%s' model but got '%s' — attempting to switch", required, current)
            switched = await agent.select_model(required)
            if switched:
                current = await agent.detect_current_model()
                logger.info("Model switched successfully: %s", current)
                return True

            # Model unavailable — offer fallback in visible mode
            if visible and current:
                print(f"\\n⚠️  '{required}' model is unavailable (current: '{current}').")
                print(f"   This usually means the model is rate-limited by Google.")
                print(f"   You can continue with '{current}' model or abort.")
                answer = input(f"   Continue with '{current}'? [y/N]: ").strip().lower()
                if answer in ("y", "yes"):
                    logger.info("User chose to continue with '%s' model", current)
                    return True

            logger.error(
                "Failed to select '%s' model (current: %s). "
                "You may need to log in first, or the model is rate-limited.",
                required, current,
            )
            return False


        # ---------------------------------------------------------------------------
        # Translation cache — JSON-based persistence for resume support
        # ---------------------------------------------------------------------------

        def _load_translation_cache(cache_path: Path) -> dict[int, str]:
            """Load chunk translations from a JSON cache file.

            Returns dict mapping chunk_index → translated_text.
            """
            if not cache_path.exists():
                return {}
            try:
                data = json.loads(cache_path.read_text(encoding="utf-8"))
                # Keys in JSON are strings; convert to int
                return {int(k): v for k, v in data.items()}
            except (json.JSONDecodeError, ValueError, KeyError):
                logger.warning("Failed to load translation cache: %s", cache_path)
                return {}


        def _save_translation_cache(
            cache_path: Path, translations: dict[int, str]
        ) -> None:
            """Save chunk translations to a JSON cache file."""
            cache_path.parent.mkdir(parents=True, exist_ok=True)
            cache_path.write_text(
                json.dumps(translations, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )


        # ---------------------------------------------------------------------------
        # Main translation loop
        # ---------------------------------------------------------------------------

        async def translate_srt_file(
            srt_path: Path,
            visible: bool = False,
        ) -> Path | None:
            """Translate a single SRT file with conversation splitting."""
            stem = srt_path.stem.replace(".ja", "")
            SRT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
            PROGRESS_DIR.mkdir(parents=True, exist_ok=True)
            output_path = SRT_OUTPUT_DIR / f"{stem}.en.srt"
            progress_path = PROGRESS_DIR / f"{stem}_progress.json"
            cache_path = PROGRESS_DIR / f"{stem}_translations.json"

            srt_text = srt_path.read_text(encoding="utf-8")
            total_blocks = count_srt_blocks(srt_text)
            logger.info("File: %s — %d blocks", srt_path.name, total_blocks)

            # Chunk into ~LINES_PER_TURN-block pieces
            chunks = chunk_srt_text(srt_text, blocks_per_chunk=LINES_PER_TURN)
            logger.info("Split into %d chunks", len(chunks))

            config = GeminiTranslatorConfig(**_kwargs)
            if visible:
                config.headless = False

            agent = GeminiTranslatorAgent(config)

            try:
                async with agent:
                    # Pre-flight: verify login
                    if not await verify_login(agent, visible):
                        logger.error("Aborting — not logged in")
                        return None

                    # Pre-flight: verify model
                    if not await verify_model(agent, visible):
                        logger.error("Aborting — wrong model")
                        return None

                    agent.init_progress(stem, len(chunks), str(progress_path))

                    # Load existing translations from JSON cache (reliable resume)
                    all_translations: dict[int, str] = _load_translation_cache(cache_path)
                    if all_translations:
                        logger.info(
                            "Resumed: loaded %d cached chunk translations",
                            len(all_translations),
                        )

                    # Always True at start — ensures system prompt is sent
                    # on the very first non-skipped chunk of this session
                    is_first_turn_in_convo = True

                    for i, chunk_text in enumerate(chunks):
                        if agent.progress and agent.progress.is_chunk_completed(i):
                            logger.info("Chunk %d/%d — already completed, skipping", i + 1, len(chunks))
                            continue

                        chunk_blocks = count_srt_blocks(chunk_text)

                        # Check if we need a new conversation
                        if agent.should_split_for_line_limit(chunk_blocks, LINES_PER_CONVO):
                            logger.info(
                                "Conversation limit (%d + %d > %d) — starting new",
                                agent.lines_in_conversation, chunk_blocks, LINES_PER_CONVO,
                            )
                            await agent.start_new_conversation()
                            is_first_turn_in_convo = True

                        # Build prompts
                        if is_first_turn_in_convo:
                            if agent.conversation_index == 0:
                                system_prompt = build_kendo_srt_system_prompt(
                                    str(DICT_FILE), lines_per_turn=LINES_PER_TURN,
                                )
                            else:
                                last_block = i * LINES_PER_TURN  # approximate
                                system_prompt = build_kendo_new_conversation_prompt(
                                    str(DICT_FILE), last_block_num=last_block,
                                    lines_per_turn=LINES_PER_TURN,
                                )
                            is_first_turn_in_convo = False
                        else:
                            system_prompt = None

                        continue_prompt = build_kendo_continue_prompt(i + 1, len(chunks))

                        chunk_obj = TranslationChunk(
                            chunk_id=f"{stem}_chunk_{i}",
                            chunk_index=i,
                            source_text=chunk_text,
                        )

                        try:
                            result = await agent.translate_text(
                                chunk_obj,
                                system_prompt=system_prompt,
                                continue_prompt=continue_prompt,
                                is_first_turn=(system_prompt is not None),
                                num_blocks=chunk_blocks,
                            )
                        except RateLimitError:
                            logger.warning("Rate limit hit at chunk %d/%d — saving progress", i, len(chunks))
                            _save_translation_cache(cache_path, all_translations)
                            print(f"\\n  Rate limited at chunk {i + 1}/{len(chunks)}.")
                            print(f"  Progress saved. Resume with: python agent.py --resume {srt_path.name}\\n")
                            return None

                        if result.success:
                            all_translations[i] = result.translated_text

                            if agent.progress:
                                agent.progress.mark_completed(i)
                                agent._save_progress()

                            # Save translation cache after each chunk for robustness
                            _save_translation_cache(cache_path, all_translations)

                            logger.info(
                                "Chunk %d/%d done (%d blocks, %.1fs)",
                                i + 1, len(chunks), chunk_blocks, result.processing_time_ms / 1000,
                            )
                        else:
                            logger.error("Chunk %d failed: %s", i, result.error)

                    # Concatenate all translations in order
                    if all_translations:
                        sorted_translations = sorted(all_translations.items())
                        full_text = "\\n\\n".join(t for _, t in sorted_translations)
                        output_path.write_text(full_text, encoding="utf-8")

                        completed = len(all_translations)
                        logger.info(
                            "Translation complete: %d/%d chunks, output: %s",
                            completed, len(chunks), output_path,
                        )
                        return output_path

            except Exception as e:
                logger.error("Translation failed: %s", e, exc_info=True)

            return None


        # ---------------------------------------------------------------------------
        # CLI
        # ---------------------------------------------------------------------------

        async def main():
            parser = argparse.ArgumentParser(
                description="Kendo SRT Translator — Gemini Translation",
                formatter_class=argparse.RawDescriptionHelpFormatter,
                epilog="""
        Examples:
            python agent.py --login                    # First-time login
            python agent.py FILE.srt                   # Translate one file
            python agent.py FILE.srt --visible         # Show browser
            python agent.py --all                      # Translate all *.ja.srt
            python agent.py --all --resume             # Resume batch
                """,
            )
            parser.add_argument("file", nargs="?", help="SRT file to translate")
            parser.add_argument("--all", action="store_true", help="Translate all *.ja.srt files")
            parser.add_argument("--resume", action="store_true", help="Resume from progress")
            parser.add_argument("--visible", action="store_true", help="Show browser")
            parser.add_argument("--login", action="store_true", help="Capture fresh Gemini login")
            args = parser.parse_args()

            if args.login:
                success = await capture_login()
                sys.exit(0 if success else 1)

            # Check for saved login session
            state_path = SCRIPT_DIR / "storage" / "gemini_storage_state.json"
            if not state_path.exists():
                print("\\n  No login session found. Running login first...\\n")
                success = await capture_login()
                if not success:
                    sys.exit(1)

            if args.all:
                files = sorted(SRT_INPUT_DIR.glob("*.ja.srt"))
                logger.info("Found %d SRT files", len(files))
                for f in files:
                    output = SRT_OUTPUT_DIR / f"{f.stem.replace('.ja', '')}.en.srt"
                    if output.exists() and not args.resume:
                        logger.info("Skipping %s (already translated)", f.name)
                        continue
                    result = await translate_srt_file(f, visible=args.visible)
                    if result is None:
                        logger.warning("Stopping batch — rate limit or error")
                        break
            elif args.file:
                path = Path(args.file)
                if not path.exists():
                    path = SRT_INPUT_DIR / args.file
                await translate_srt_file(path, visible=args.visible)
            else:
                parser.print_help()


        if __name__ == "__main__":
            asyncio.run(main())
    ''')
    agent_path = pkg_dir / "agent.py"
    agent_path.write_text(script, encoding="utf-8")
    agent_path.chmod(0o755)


def main():
    parser = argparse.ArgumentParser(description="Compile Kendo SRT Translator agent")
    parser.add_argument(
        "--output-dir", "-o",
        default=str(PROJECT_ROOT / "compiled_agents"),
        help="Output directory for the package (default: compiled_agents/)",
    )
    args = parser.parse_args()
    compile_kendo_translator(Path(args.output_dir))


if __name__ == "__main__":
    main()
