#!/usr/bin/env python3
"""Compile a self-contained Claude Kendo SRT Translator agent package.

This script creates a distributable package for the kendo SRT translation
task using Claude. The resulting package includes:

- agent.py: Executable translation script
- config.json: Modifiable configuration
- storage/: Auth state (claude_storage_state.json)
- kendo_dict.md: Kendo dictionary
- requirements.txt: Python dependencies
- srt_files/: Input SRT files
- translated/: Output directory
- progress/: Resumable progress files

Usage:
    python scripts/compile_kendo_translator_claude.py [--output-dir DIR]
"""

import argparse
import json
import shutil
import sys
import textwrap
from pathlib import Path

# Add project root for imports
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from universal_agents.compiler import (
    AgentCompiler,
    AgentPackager,
    CapabilityResolver,
    CompiledAgent,
    ConfigBuilder,
    AgentAssembler,
    ResolvedComponents,
    UserRequirements,
)


def compile_kendo_translator_claude(output_dir: Path) -> Path:
    """Compile and package the Claude kendo SRT translator agent."""

    # 1. Define requirements
    req = UserRequirements(
        use_case="translation",
        needs_file_upload=False,
        needs_thinking=True,
        needs_json_output=False,
        cost_sensitivity="free",
        provider_preference="claude",
        output_format="package",
        package_dir=str(output_dir),
        package_name="claude_kendo_srt_translator",
        auth_available={"claude_storage": True},
    )
    req.apply_use_case_defaults()

    # 2. Resolve components
    resolver = CapabilityResolver()
    components = resolver.resolve(req)

    # 3. Override config for kendo SRT task
    config_kwargs = {
        "headless": True,
        "timeout": 600,
        "max_turns_per_conversation": 20,
        "source_language": "ja",
        "target_language": "en",
        "translation_mode": "transcript",
        "chunk_size": 2000,
        "overlap_chars": 100,
        "extract_thinking": True,
        "storage_state": str(PROJECT_ROOT / "storage" / "claude_storage_state.json"),
    }

    # 4. Create compiled agent
    compiled = CompiledAgent(
        provider="claude",
        agent_class_name=components.agent_class_name,
        config_class_name=components.config_class_name,
        config_kwargs=config_kwargs,
        capabilities=["translation", "file_upload", "thinking_extraction"],
        script="# Replaced by custom script below",
    )

    # 5. Package it
    packager = AgentPackager(project_root=PROJECT_ROOT)
    pkg_dir = packager.package(compiled, components, req, output_dir, "claude_kendo_srt_translator")

    # 6. Copy the kendo dictionary into the package
    dict_src = PROJECT_ROOT / "storage" / "test_srt_files" / "Trilingual Kendo Dictionary.md"
    if dict_src.exists():
        shutil.copy2(dict_src, pkg_dir / "kendo_dict.md")

    # 7. Copy Claude storage state
    claude_state = PROJECT_ROOT / "storage" / "claude_storage_state.json"
    if claude_state.exists():
        storage_dir = pkg_dir / "storage"
        storage_dir.mkdir(exist_ok=True)
        shutil.copy2(claude_state, storage_dir / "claude_storage_state.json")

    # 8. Write the custom production run script
    _write_run_script(pkg_dir)

    # 9. Update config.json with kendo-specific fields
    config_path = pkg_dir / "config.json"
    config = json.loads(config_path.read_text())
    config["kendo"] = {
        "dictionary_file": "kendo_dict.md",
        "lines_per_conversation": 400,
        "lines_per_turn": 50,
        "srt_input_dir": "srt_files/",
        "srt_output_dir": "translated/",
    }
    config_path.write_text(json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8")

    # 10. Create input/output directories
    (pkg_dir / "srt_files").mkdir(exist_ok=True)
    (pkg_dir / "translated").mkdir(exist_ok=True)
    (pkg_dir / "progress").mkdir(exist_ok=True)

    print(f"\n✅ Package created at: {pkg_dir}")
    print(f"   Files: {list(p.name for p in sorted(pkg_dir.iterdir()))}")
    print(f"\n   To use:")
    print(f"   1. Copy SRT files into: {pkg_dir / 'srt_files/'}")
    print(f"   2. Run: cd {pkg_dir} && python agent.py srt_files/YOUR_FILE.srt")
    print(f"   3. Or batch: cd {pkg_dir} && python agent.py --all")
    return pkg_dir


def _write_run_script(pkg_dir: Path) -> None:
    """Write the production agent.py for Claude kendo SRT translation."""
    script = textwrap.dedent('''\
        #!/usr/bin/env python3
        """Kendo SRT Translator — Self-contained Claude translation agent.

        Translates Japanese SRT subtitle files to English using Claude
        with kendo terminology dictionary context.

        Generated by universal-agents compiler.
        Edit config.json to change behavior.

        Usage:
            python agent.py FILE.srt              # Translate one file
            python agent.py --all                  # Translate all *.ja.srt in srt_files/
            python agent.py --resume               # Resume after rate limit
            python agent.py --visible FILE.srt     # Show browser
        """

        import argparse
        import asyncio
        import json
        import logging
        import re
        import sys
        import time
        from datetime import datetime
        from pathlib import Path

        SCRIPT_DIR = Path(__file__).resolve().parent

        # Load config
        with open(SCRIPT_DIR / "config.json", encoding="utf-8") as f:
            CONFIG = json.load(f)

        # Resolve paths relative to package
        _kwargs = dict(CONFIG["config_kwargs"])
        _state = SCRIPT_DIR / "storage" / Path(_kwargs.get("storage_state", "")).name
        if _state.exists():
            _kwargs["storage_state"] = str(_state)

        _kendo = CONFIG.get("kendo", {})
        DICT_FILE = SCRIPT_DIR / _kendo.get("dictionary_file", "kendo_dict.md")
        LINES_PER_CONVO = _kendo.get("lines_per_conversation", 400)
        LINES_PER_TURN = _kendo.get("lines_per_turn", 50)
        SRT_INPUT_DIR = SCRIPT_DIR / _kendo.get("srt_input_dir", "srt_files/")
        SRT_OUTPUT_DIR = SCRIPT_DIR / _kendo.get("srt_output_dir", "translated/")
        PROGRESS_DIR = SCRIPT_DIR / "progress"

        logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
        logger = logging.getLogger(__name__)

        # Imports
        from universal_agents.providers.claude.config import ClaudeTranslatorConfig
        from universal_agents.providers.claude.translator import (
            ClaudeTranslatorAgent,
            ProgressState,
            TranslationChunk,
        )
        from universal_agents.core.srt_utils import parse_srt_blocks, chunk_srt_text, normalize_srt_text
        from universal_agents.core.kendo_context import (
            build_kendo_srt_system_prompt,
            build_kendo_continue_prompt,
            build_kendo_new_conversation_prompt,
        )


        def count_srt_blocks(text: str) -> int:
            return len(re.findall(r"^\\d+$", text, re.MULTILINE))


        async def verify_login(agent: ClaudeTranslatorAgent, visible: bool) -> bool:
            """Verify that Claude is logged in by checking for the input field."""
            page = await agent._agent.browser_mgr.ensure_page()

            # Check if the chat input is visible (means we're logged in)
            try:
                await page.wait_for_selector(
                    "div.ProseMirror[contenteditable='true']",
                    state="visible",
                    timeout=15_000,
                )
                logger.info("Claude login verified — chat input visible")
                return True
            except Exception:
                pass

            # Check for login-required indicators
            login_indicators = [
                'a[href*="login"]',
                'button:has-text("Log in")',
                'button:has-text("Sign in")',
                '[data-testid="login-button"]',
            ]
            for sel in login_indicators:
                try:
                    loc = page.locator(sel).first
                    if await loc.count() > 0:
                        if not visible:
                            logger.error(
                                "Not logged in to Claude. Run with --visible to log in manually, "
                                "or refresh storage state."
                            )
                            return False
                        break
                except Exception:
                    continue

            if not visible:
                logger.error("Could not verify Claude login")
                return False

            # Visible mode: prompt for manual login
            logger.warning("Not logged in. Please log in manually in the browser window.")
            print("\\n⚠️  Not logged in to Claude!")
            print("   Please log in manually in the browser window.")
            print("   Waiting for login (checking every 5s)...\\n")
            for attempt in range(60):
                await asyncio.sleep(5)
                try:
                    await page.wait_for_selector(
                        "div.ProseMirror[contenteditable='true']",
                        state="visible",
                        timeout=5_000,
                    )
                    logger.info("Login detected after manual login")
                    # Save updated cookies
                    try:
                        ctx = page.context
                        state = await ctx.storage_state()
                        state_file = SCRIPT_DIR / "storage" / "claude_storage_state.json"
                        state_file.write_text(
                            json.dumps(state, indent=2, ensure_ascii=False),
                            encoding="utf-8",
                        )
                        logger.info("Updated storage state saved")
                    except Exception as e:
                        logger.debug("Could not save storage state: %s", e)
                    return True
                except Exception:
                    pass
                if attempt % 6 == 5:
                    print(f"   Still waiting... ({(attempt + 1) * 5}s)")
            logger.error("Login timeout after 5 minutes")
            return False


        async def translate_srt_file(
            srt_path: Path,
            visible: bool = False,
        ) -> Path | None:
            """Translate a single SRT file with conversation splitting."""
            stem = srt_path.stem.replace(".ja", "")
            SRT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
            PROGRESS_DIR.mkdir(parents=True, exist_ok=True)
            output_path = SRT_OUTPUT_DIR / f"{stem}.en.srt"
            progress_path = PROGRESS_DIR / f"{stem}_progress.json"

            srt_text = srt_path.read_text(encoding="utf-8")
            total_blocks = count_srt_blocks(srt_text)
            logger.info("File: %s — %d blocks", srt_path.name, total_blocks)

            # Chunk into ~LINES_PER_TURN-block pieces
            chunks = chunk_srt_text(srt_text, blocks_per_chunk=LINES_PER_TURN)
            logger.info("Split into %d chunks", len(chunks))

            config = ClaudeTranslatorConfig(**_kwargs)
            if visible:
                config.headless = False

            agent = ClaudeTranslatorAgent(config)

            try:
                async with agent:
                    # Pre-flight: verify login
                    if not await verify_login(agent, visible):
                        logger.error("Aborting — not logged in")
                        return None

                    agent.init_progress(stem, len(chunks), str(progress_path))

                    all_translations = []
                    is_first_turn_in_convo = True
                    lines_in_conversation = 0

                    for i, chunk_text in enumerate(chunks):
                        if agent.progress and agent.progress.is_chunk_completed(i):
                            # Find existing result
                            for r in agent.results:
                                if r.chunk_index == i and r.success:
                                    all_translations.append((i, r.translated_text))
                                    break
                            continue

                        chunk_blocks = count_srt_blocks(chunk_text)

                        # Check if we need a new conversation (line-based or turn-based)
                        if (lines_in_conversation + chunk_blocks) > LINES_PER_CONVO or agent.should_split_conversation():
                            logger.info(
                                "Conversation limit — starting new (lines: %d, turns: %d)",
                                lines_in_conversation, agent.turn_in_conversation,
                            )
                            await agent.start_new_conversation()
                            is_first_turn_in_convo = True
                            lines_in_conversation = 0

                        # Build prompts
                        if is_first_turn_in_convo:
                            if agent.conversation_index == 0:
                                system_prompt = build_kendo_srt_system_prompt(
                                    str(DICT_FILE), lines_per_turn=LINES_PER_TURN,
                                )
                            else:
                                last_block = i * LINES_PER_TURN
                                system_prompt = build_kendo_new_conversation_prompt(
                                    str(DICT_FILE), last_block_num=last_block,
                                    lines_per_turn=LINES_PER_TURN,
                                )
                            is_first_turn_in_convo = False
                        else:
                            system_prompt = None

                        continue_prompt = build_kendo_continue_prompt(i + 1, len(chunks))

                        chunk_obj = TranslationChunk(
                            chunk_id=f"{stem}_chunk_{i}",
                            chunk_index=i,
                            source_text=chunk_text,
                        )

                        result = await agent.translate_text(
                            chunk_obj,
                            system_prompt=system_prompt,
                            continue_prompt=continue_prompt,
                            is_first_turn=(system_prompt is not None),
                        )

                        if result.success:
                            all_translations.append((i, result.translated_text))
                            lines_in_conversation += chunk_blocks
                            logger.info(
                                "Chunk %d/%d done (%d blocks, %.1fs)",
                                i + 1, len(chunks), chunk_blocks, result.processing_time_ms / 1000,
                            )
                        else:
                            logger.error("Chunk %d failed: %s", i, result.error)

                    # Concatenate all translations and normalize SRT formatting
                    if all_translations:
                        all_translations.sort(key=lambda x: x[0])
                        full_text = "\\n\\n".join(t for _, t in all_translations)
                        full_text = normalize_srt_text(full_text)
                        output_path.write_text(full_text, encoding="utf-8")
                        logger.info("Output written to: %s", output_path)
                        return output_path

            except Exception as e:
                logger.error("Translation failed: %s", e, exc_info=True)

            return None


        async def main():
            parser = argparse.ArgumentParser(description="Kendo SRT Translator (Claude)")
            parser.add_argument("file", nargs="?", help="SRT file to translate")
            parser.add_argument("--all", action="store_true", help="Translate all *.ja.srt files")
            parser.add_argument("--resume", action="store_true", help="Resume from progress")
            parser.add_argument("--visible", action="store_true", help="Show browser")
            args = parser.parse_args()

            if args.all:
                files = sorted(SRT_INPUT_DIR.glob("*.ja.srt"))
                logger.info("Found %d SRT files", len(files))
                for f in files:
                    output = SRT_OUTPUT_DIR / f"{f.stem.replace('.ja', '')}.en.srt"
                    if output.exists() and not args.resume:
                        logger.info("Skipping %s (already translated)", f.name)
                        continue
                    result = await translate_srt_file(f, visible=args.visible)
                    if result is None:
                        logger.warning("Stopping batch — error")
                        break
            elif args.file:
                path = Path(args.file)
                if not path.exists():
                    path = SRT_INPUT_DIR / args.file
                await translate_srt_file(path, visible=args.visible)
            else:
                parser.print_help()


        if __name__ == "__main__":
            asyncio.run(main())
    ''')
    agent_path = pkg_dir / "agent.py"
    agent_path.write_text(script, encoding="utf-8")
    agent_path.chmod(0o755)


def main():
    parser = argparse.ArgumentParser(description="Compile Claude Kendo SRT Translator agent")
    parser.add_argument(
        "--output-dir", "-o",
        default=str(PROJECT_ROOT / "compiled_agents"),
        help="Output directory for the package (default: compiled_agents/)",
    )
    args = parser.parse_args()
    compile_kendo_translator_claude(Path(args.output_dir))


if __name__ == "__main__":
    main()
