#!/usr/bin/env python3
"""Compile a self-contained Perplexity Deep Research agent package.

This script uses the agent compiler to create a distributable package
for the Perplexity deep-research task.  The resulting package includes:

- agent.py: Executable research script
- config.json: Modifiable configuration
- storage/: Auth state (pplx_storage_state.json)
- requirements.txt: Python dependencies
- source_spec.json: Recompilation spec
- README.md: Usage instructions
- reports/: Output directory for Markdown research reports

Usage:
    python scripts/compile_pplx_research.py
    python scripts/compile_pplx_research.py --output-dir compiled_agents/
"""

import argparse
import json
import textwrap
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from universal_agents.compiler import (
    AgentPackager,
    CapabilityResolver,
    CompiledAgent,
    UserRequirements,
)


def compile_pplx_research(output_dir: Path) -> Path:
    """Compile and package the Perplexity deep research agent."""

    # 1. Define requirements
    req = UserRequirements(
        use_case="research",
        needs_citations=True,
        needs_file_upload=False,
        needs_thinking=False,
        needs_json_output=False,
        cost_sensitivity="free",
        provider_preference="perplexity",
        output_format="package",
        package_dir=str(output_dir),
        package_name="pplx_deep_research",
        auth_available={"pplx_storage": True},  # Session captured via --login at runtime
    )
    req.apply_use_case_defaults()

    # 2. Resolve components
    resolver = CapabilityResolver()
    components = resolver.resolve(req)

    # 3. Config for deep research
    config_kwargs = {
        "headless": True,
        "timeout": 60,           # Standard search timeout (seconds)
        "storage_state": "",     # Filled in after --login
        "extract_citations": True,
        "research_mode": "auto", # Try Deep Research, fall back to standard
        "output_dir": "reports/",
        "max_research_wait": 300,  # 5 minutes max for Deep Research
    }

    # 4. Create compiled agent
    compiled = CompiledAgent(
        provider="perplexity",
        agent_class_name=components.agent_class_name,
        config_class_name=components.config_class_name,
        config_kwargs=config_kwargs,
        capabilities=["research", "citations", "deep_research"],
        script="# Replaced by custom script below",
    )

    # 5. Package it
    packager = AgentPackager(project_root=PROJECT_ROOT)
    pkg_dir = packager.package(
        compiled, components, req, output_dir, "pplx_deep_research"
    )

    # 6. Write the custom production run script
    _write_run_script(pkg_dir)

    # 7. Update config.json with research-specific fields
    config_path = pkg_dir / "config.json"
    config = json.loads(config_path.read_text())
    config["research"] = {
        "output_dir": "reports/",
        "max_research_wait": 300,
    }
    config_path.write_text(json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8")

    # 8. Create required directories
    for d in ("reports", "storage"):
        (pkg_dir / d).mkdir(exist_ok=True)
        gitkeep = pkg_dir / d / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.touch()

    # 9. Write README
    _write_readme(pkg_dir)

    print(f"\n✅  Package created at: {pkg_dir}")
    print(f"   Files: {sorted(p.name for p in pkg_dir.iterdir())}")
    print(f"\n   To use:")
    print(f"   1. First login: python {pkg_dir / 'agent.py'} --login")
    print(f"   2. Research:    python {pkg_dir / 'agent.py'} 'What is fusion energy?'")
    print(f"   3. Reports are saved to: {pkg_dir / 'reports/'}")
    return pkg_dir


def _write_run_script(pkg_dir: Path) -> None:
    """Write the production agent.py for Perplexity deep research."""
    script = textwrap.dedent('''\
        #!/usr/bin/env python3
        """Perplexity Deep Research Agent — Self-contained research agent.

        Submits a research query to Perplexity, attempts to use the
        "Deep Research" mode (with automatic fallback to standard search),
        and saves the result as a Markdown report.

        Generated by universal-agents compiler.
        Edit config.json to change behavior.

        Usage:
            python agent.py "What are the latest advances in fusion energy?"
            python agent.py --login                         # Capture Perplexity session
            python agent.py "Query" --visible               # Show browser
            python agent.py "Query" --mode deep             # Force Deep Research mode
            python agent.py "Query" --mode standard         # Force standard search
            python agent.py "Query" --output results/       # Custom output directory
        """

        import argparse
        import asyncio
        import json
        import logging
        import sys
        from pathlib import Path

        SCRIPT_DIR = Path(__file__).resolve().parent

        # ---------------------------------------------------------------------------
        # Load config
        # ---------------------------------------------------------------------------
        with open(SCRIPT_DIR / "config.json", encoding="utf-8") as f:
            CONFIG = json.load(f)

        _kwargs = dict(CONFIG["config_kwargs"])

        # Resolve storage state relative to package
        _state = SCRIPT_DIR / "storage" / "pplx_storage_state.json"
        if _state.exists():
            _kwargs["storage_state"] = str(_state)

        _research_cfg = CONFIG.get("research", {})
        OUTPUT_DIR = SCRIPT_DIR / _research_cfg.get("output_dir", "reports/")
        MAX_WAIT = _research_cfg.get("max_research_wait", 300)

        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s %(levelname)s %(message)s",
        )
        logger = logging.getLogger(__name__)

        # ---------------------------------------------------------------------------
        # Imports
        # ---------------------------------------------------------------------------
        from universal_agents.providers.pplx.config import PerplexityResearchConfig
        from universal_agents.providers.pplx.research import PerplexityResearchAgent


        # ---------------------------------------------------------------------------
        # Login helpers
        # ---------------------------------------------------------------------------

        async def capture_login() -> bool:
            """Open a visible browser so the user can log in to Perplexity."""
            logger.info("Opening browser for Perplexity login...")
            config = PerplexityResearchConfig(**{**_kwargs, "headless": False})
            agent = PerplexityResearchAgent(config)

            try:
                async with agent:
                    page = await agent.browser_mgr.ensure_page()
                    await page.goto("https://www.perplexity.ai")
                    await page.wait_for_timeout(2000)

                    print("\\n" + "=" * 60)
                    print("  PERPLEXITY LOGIN")
                    print("=" * 60)
                    print("  Please sign in to Perplexity in the browser window.")
                    print("  After login, press Enter here to save the session.")
                    print("=" * 60 + "\\n")

                    input("  Press Enter after you have logged in... ")

                    storage_dir = SCRIPT_DIR / "storage"
                    storage_dir.mkdir(parents=True, exist_ok=True)
                    state_file = storage_dir / "pplx_storage_state.json"

                    ctx = page.context
                    state = await ctx.storage_state()
                    state_file.write_text(
                        json.dumps(state, indent=2, ensure_ascii=False),
                        encoding="utf-8",
                    )
                    _kwargs["storage_state"] = str(state_file)
                    logger.info("Session saved: %s", state_file)
                    print(f"\\n  Session saved to {state_file}\\n")
                    return True
            except Exception as exc:
                logger.error("Login capture failed: %s", exc)
                return False


        # ---------------------------------------------------------------------------
        # Research
        # ---------------------------------------------------------------------------

        async def run_research(query: str, mode: str, output_dir: Path, visible: bool) -> int:
            """Run a single research query and save the report."""
            kwargs = dict(_kwargs)
            if visible:
                kwargs["headless"] = False

            config = PerplexityResearchConfig(
                **kwargs,
                research_mode=mode,
                output_dir=str(output_dir),
                max_research_wait=MAX_WAIT,
            )

            output_dir.mkdir(parents=True, exist_ok=True)

            async with PerplexityResearchAgent(config) as agent:
                logger.info("Researching: %s", query)
                try:
                    report = await agent.research(query, save=True)
                    print(f"\\n{'=' * 60}")
                    print(f"  Research complete ({report.mode_used} mode, {report.elapsed_seconds:.1f}s)")
                    print(f"  Citations: {len(report.citations)}")
                    saved_path = report.save(output_dir)
                    print(f"  Report saved: {saved_path}")
                    print(f"{'=' * 60}\\n")
                    print(report.content[:2000])
                    if len(report.content) > 2000:
                        print(f"\\n  ... (truncated, full report in {saved_path})")
                    return 0
                except Exception as exc:
                    logger.error("Research failed: %s", exc)
                    return 1


        # ---------------------------------------------------------------------------
        # CLI
        # ---------------------------------------------------------------------------

        def main() -> int:
            parser = argparse.ArgumentParser(
                description="Perplexity Deep Research Agent",
                formatter_class=argparse.RawDescriptionHelpFormatter,
            )
            parser.add_argument("query", nargs="?", help="Research query / topic")
            parser.add_argument(
                "--login", action="store_true", help="Capture Perplexity login session"
            )
            parser.add_argument(
                "--visible", action="store_true", help="Show browser window"
            )
            parser.add_argument(
                "--mode",
                choices=["deep", "standard", "auto"],
                default=None,
                help="Research mode override (default: from config.json)",
            )
            parser.add_argument(
                "--output",
                type=Path,
                default=None,
                help="Output directory for reports (default: reports/)",
            )
            args = parser.parse_args()

            if args.login:
                return asyncio.run(capture_login())

            if not args.query:
                parser.error("A research query is required (or use --login)")

            mode = args.mode or _kwargs.get("research_mode", "auto")
            out_dir = args.output or OUTPUT_DIR

            return asyncio.run(run_research(args.query, mode, out_dir, args.visible))


        if __name__ == "__main__":
            sys.exit(main())
    ''')
    (pkg_dir / "agent.py").write_text(script, encoding="utf-8")


def _write_readme(pkg_dir: Path) -> None:
    readme = textwrap.dedent("""\
        # Perplexity Deep Research Agent

        A self-contained agent that submits research queries to [Perplexity AI](https://www.perplexity.ai),
        attempts to enable **Deep Research** mode (with automatic fallback to standard search),
        and saves structured Markdown reports with citations.

        ## Quick Start

        ### 1. Install dependencies

        ```bash
        pip install -r requirements.txt
        playwright install chromium
        ```

        ### 2. Log in to Perplexity

        ```bash
        python agent.py --login
        ```

        A browser window will open.  Sign in to Perplexity, then press **Enter** in the
        terminal.  Your session is saved to `storage/pplx_storage_state.json`.

        ### 3. Run a research query

        ```bash
        python agent.py "What are the latest advances in fusion energy?"
        ```

        The report is saved to `reports/` as a Markdown file.

        ## Options

        | Flag | Description |
        |---|---|
        | `--login` | Capture a fresh Perplexity login session |
        | `--visible` | Show the browser window |
        | `--mode deep` | Force Deep Research mode |
        | `--mode standard` | Force standard Perplexity search |
        | `--mode auto` | Try Deep Research, fall back to standard (default) |
        | `--output DIR` | Save reports to a custom directory |

        ## Configuration

        Edit `config.json` to change defaults:

        ```json
        {
          "config_kwargs": {
            "headless": true,
            "research_mode": "auto",
            "max_research_wait": 300
          }
        }
        ```

        ## Output

        Reports are Markdown files with:

        - Query, mode, duration metadata
        - Full research response
        - Numbered citations with URLs
    """)
    (pkg_dir / "README.md").write_text(readme, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile the Perplexity deep research agent")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "compiled_agents",
        help="Directory to place the compiled agent package (default: compiled_agents/)",
    )
    args = parser.parse_args()
    compile_pplx_research(args.output_dir)


if __name__ == "__main__":
    main()
